In [2]:
import ibm_db
import ibm_db_sa
import pandas as pd

%reload_ext sql

%sql ibm_db_sa://wsy87409:3jO6uNH6THqWZg7O@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL

In [4]:
%%sql

SELECT TABSCHEMA, TABNAME, CREATE_TIME 
    FROM syscat.tables
        WHERE TABSCHEMA = 'WSY87409';

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('WSY87409', 'PETSALE', datetime.datetime(2022, 12, 8, 14, 56, 58, 6205)),
 ('WSY87409', 'TEST', datetime.datetime(2022, 12, 8, 14, 0, 50, 629587)),
 ('WSY87409', 'TEST_1', datetime.datetime(2022, 12, 8, 14, 8, 15, 236080)),
 ('WSY87409', 'EMPLOYEES', datetime.datetime(2022, 12, 8, 22, 29, 41, 348782)),
 ('WSY87409', 'JOB_HISTORY', datetime.datetime(2022, 12, 8, 22, 29, 41, 579077)),
 ('WSY87409', 'JOBS', datetime.datetime(2022, 12, 8, 22, 29, 41, 846565)),
 ('WSY87409', 'DEPARTMENTS', datetime.datetime(2022, 12, 8, 22, 29, 42, 99242)),
 ('WSY87409', 'LOCATIONS', datetime.datetime(2022, 12, 8, 22, 29, 42, 347790)),
 ('WSY87409', 'PETRESCUE', datetime.datetime(2022, 12, 10, 16, 28, 5, 14848)),
 ('WSY87409', 'INTERNATIONAL_STUDENT_TEST_SCORES', datetime.datetime(2022, 12, 13, 10, 21, 16, 750364)),
 ('WSY87409', 'CHICAGO_DATA', datetime.datetime(2022, 12, 13, 15, 22, 54, 164075)),
 ('WSY87409', 'INSTRUCTOR', datetime.datetime(2022, 12, 13, 7, 23, 5, 923981)),
 ('WSY87409', 'SCHOOLS', datetime.datetime(2022, 12, 14, 8, 58, 52, 634466)),
 ('WSY87409', 'CENSUS_DATA', datetime.datetime(2022, 12, 15, 10, 21, 53, 569965)),
 ('WSY87409', 'CHICAGO_CRIME_DATA', datetime.datetime(2022, 12, 15, 10, 23, 38, 580361)),
 ('WSY87409', 'CHICAGO_PUBLIC_SCHOOLS', datetime.datetime(2022, 12, 15, 10, 24, 58, 748940))]

In [128]:
%%sql 

SELECT * FROM syscat.columns
    WHERE TABNAME = 'CHICAGO_CRIME_DATA';

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('WSY87409', 'CHICAGO_CRIME_DATA', 'ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'CASE_NUMBER', 1, 'SYSIBM  ', 'VARCHAR', 8, 0, 'OCTETS', 8, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'DATE', 2, 'SYSIBM  ', 'DATE', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'BLOCK', 3, 'SYSIBM  ', 'VARCHAR', 35, 0, 'OCTETS', 35, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'IUCR', 4, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'PRIMARY_TYPE', 5, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'DESCRIPTION', 6, 'SYSIBM  ', 'VARCHAR', 46, 0, 'OCTETS', 46, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'LOCATION_DESCRIPTION', 7, 'SYSIBM  ', 'VARCHAR', 33, 0, 'OCTETS', 33, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'ARREST', 8, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'DOMESTIC', 9, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'BEAT', 10, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'DISTRICT', 11, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'WARD', 12, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'COMMUNITY_AREA_NUMBER', 13, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'FBICODE', 14, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'X_COORDINATE', 15, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'Y_COORDINATE', 16, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'YEAR', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'LATITUDE', 18, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'LONGITUDE', 19, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('WSY87409', 'CHICAGO_CRIME_DATA', 'LOCATION', 20, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

**P1**: find the total number of crimes in the CRIME table.

In [13]:
%%sql 
SELECT * FROM CHICAGO_CRIME_DATA;

SELECT COUNT(*) AS total_num_crime FROM CHICAGO_CRIME_DATA;

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.
Done.

[(533,)]

**P2**: list community areas with **per capita** income less than 11000.

In [16]:
%%sql 

SELECT community_area_name, per_capita_income FROM CENSUS_DATA
    WHERE per_capita_income < 11000;

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

**P3**: list all case numbers for crimes *involving minors*.

In [41]:
%%sql 
SELECT case_number, DESCRIPTION FROM CHICAGO_CRIME_DATA

    WHERE DESCRIPTION LIKE '%MINOR%';

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('HL266884', 'SELL/GIVE/DEL LIQUOR TO MINOR'),
 ('HK238408', 'ILLEGAL CONSUMPTION BY MINOR')]

**P4**: list all kidnapping crimes involving a child.

In [50]:
%%sql

SELECT case_number, primary_type, DESCRIPTION FROM CHICAGO_CRIME_DATA 
    where primary_type like '%KIDNAPPING';

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('HN144152', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER')]

**P5**: what kind of crimes were recorded at *schools*.

In [11]:
%%sql 
SELECT DISTINCT primary_type FROM CHICAGO_CRIME_DATA 
    WHERE location_description LIKE '%SCHOOL%'
        ORDER BY PRIMARY_TYPE

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('ASSAULT',),
 ('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('CRIMINAL TRESPA',),
 ('NARCOTICS',),
 ('PUBLIC PEACE VI',)]

**P6**: list the *average safety score* for all types of schools

In [84]:
%%sql 

SELECT "Elementary, Middle, or High School", AVG(SAFETY_SCORE) AS average_safety_score
    FROM CHICAGO_PUBLIC_SCHOOLS
        GROUP BY "Elementary, Middle, or High School";

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('ES', 49), ('HS', 49), ('MS', 48)]

**P7**: list 5 community areas wiht highest % of households *below poverty*.

In [89]:
%%sql 
SELECT community_area_name , percent_households_below_poverty
    FROM CENSUS_DATA
        ORDER BY percent_households_below_poverty DESC LIMIT 5;

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('Riverdale', Decimal('56.5')),
 ('Fuller Park', Decimal('51.2')),
 ('Englewood', Decimal('46.6')),
 ('North Lawndale', Decimal('43.1')),
 ('East Garfield Park', Decimal('42.4'))]

**P8**: which community area(number) is most crime prone?

In [116]:
%%sql 

SELECT community_area_number, count(*) as total_crime_number 
    FROM CHICAGO_CRIME_DATA
        GROUP BY community_area_number
            ORDER BY total_crime_number DESC LIMIT 1

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[(25, 43)]

**P9**: use a `sub_query` to find the name of the community area with highest *hardship index*.

In [127]:
%%sql

SELECT COMMUNITY_AREA_NAME, HARDSHIP_INDEX 
    FROM CENSUS_DATA
        WHERE HARDSHIP_INDEX = (select max(HARDSHIP_INDEX) from CENSUS_DATA)

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('Riverdale', 98)]

**P10**: use a `sub_query` to determine the community area name with most number of crimes.

In [144]:
%%sql 

SELECT COMMUNITY_AREA_NAME
    FROM CENSUS_DATA
        WHERE COMMUNITY_AREA_NUMBER =
            (select community_area_number
                from CHICAGO_CRIME_DATA
                    group by community_area_number
                        order by count(community_area_number) DESC LIMIT 1)

 * ibm_db_sa://wsy87409:***@55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;security=SSL
Done.

[('Austin',)]